/**
 * Port of dashboard.py v10 (analyze / finance / forecast / savings_track /
 * solar_curve), with the flat tariff upgraded from a single blended rate to
 * the real MEA Type 1.1.2 tiered ladder + Ft + VAT (2026-06). Formulas must
 * NOT drift from scripts/gen_energy_expected.py — unit tests compare against
 * expected values generated by that script on the same fixture.
 *
 * Time rule (load-bearing): every hour/day/weekday is computed in
 * Asia/Bangkok (UTC+7) via fixed-offset arithmetic on ms epochs. Never use
 * local Date getters — this code runs on Workers (UTC), in CI, and in any
 * visitor's browser, and all three must agree.
 */

export const ENERGY_CONST = {
	SCALE: 0.01, // raw counter unit → kWh
	MAX_GAP_MS: 2 * 3600 * 1000, // deltas across gaps >2h don't enter the profile
	FT_RATE: 0.1623, // ฿/kWh ค่า Ft งวด พ.ค.–ส.ค. 2569 (กกพ. ปรับทุก 4 เดือน — อัปเดตที่นี่)
	VAT: 1.07, // ภาษีมูลค่าเพิ่ม 7% คูณท้ายบิล (ค่าพลังงาน + Ft + ค่าบริการ)
	FLAT_FIXED: 40.9, // ฿/mo flat service Type 1.1.2: 38.22 + VAT 7% (เท่ากับฝั่ง TOU)
	TOU_ON: 5.81, // ฿/kWh TOU on-peak (Mon–Fri 09:00–21:59)
	TOU_OFF: 2.99, // ฿/kWh TOU off-peak
	TOU_FIXED: 40.9, // ฿/mo TOU service fee (Type 1.2: 38.22 + VAT 7%)
	BLUERING: 699.0, // ฿/mo solar subscription
	SOLAR_KWH_D: 8.0, // kWh/day from 2kW solar
	WEEKDAYS_MO: 22, // weekdays per month (solar offsets on-peak)
	WEEKENDS_MO: 8, // weekend days per month (solar offsets off-peak)
	METER_COST: 3350.0, // ฿ one-time TOU meter cost
	MEA_MONTHLY_KWH: 1100.0, // whole-house billing baseline (MEA bill)
	USE_MEA_BASELINE: true,
} as const;

const C = ENERGY_CONST;

// ---------------- flat tariff: MEA Type 1.1.2 tiered ladder ----------------

/** ขั้นบันได กฟน. ประเภท 1.1.2 (>150 หน่วย/เดือน): [เพดานหน่วยสะสม, ฿/kWh ก่อน Ft+VAT] */
export const FLAT_TIERS: ReadonlyArray<readonly [number, number]> = [
	[150, 3.2484],
	[400, 4.2218],
	[Infinity, 4.4217],
];

/** ค่าพลังงาน flat ทั้งเดือน: ขั้นบันได + Ft ต่อหน่วย, รวม VAT — ไม่รวมค่าบริการ */
export function flatEnergyBaht(kwhMonth: number): number {
	let cost = 0;
	let prev = 0;
	for (const [upto, rate] of FLAT_TIERS) {
		const units = Math.min(kwhMonth, upto) - prev;
		if (units <= 0) break;
		cost += units * rate;
		prev = upto;
	}
	return (cost + kwhMonth * C.FT_RATE) * C.VAT;
}

/** อัตราเฉลี่ยจริง ฿/kWh ณ ปริมาณรายเดือนนั้น (ใช้เกลี่ยบิลขั้นบันไดลงรายวัน) */
export function flatAvgRate(kwhMonth: number): number {
	return kwhMonth > 0
		? flatEnergyBaht(kwhMonth) / kwhMonth
		: (FLAT_TIERS[0][1] + C.FT_RATE) * C.VAT;
}

// ---------------- Bangkok time (fixed offset — no local Date getters) ----------------

const BKK_MS = 7 * 3600 * 1000;
const DAY_MS = 86400 * 1000;

/** Bangkok calendar day as integer (days since epoch in BKK) */
export const dayNum = (ms: number): number => Math.floor((ms + BKK_MS) / DAY_MS);
/** Bangkok hour 0–23 */
export const hourOf = (ms: number): number => Math.floor((ms + BKK_MS) / 3600_000) % 24;
/** Python datetime.weekday(): Mon=0 … Sun=6 (epoch day 0 = Thu = 3) */
export const weekdayOf = (day: number): number => (((day + 3) % 7) + 7) % 7;
/** Bangkok minute-of-hour 0–59 */
export const minuteOf = (ms: number): number => Math.floor((ms + BKK_MS) / 60_000) % 60;
/** MEA TOU Type 1.2: on-peak = weekday (Mon–Fri) 09:00–21:59 BKK. Single
 *  source of truth — UI components must use this, not re-derive the window. */
export const isOnPeakHour = (wd: number, h: number): boolean => wd < 5 && h >= 9 && h < 22;
/** dayNum for a BKK calendar date */
export const dayNumFromYmd = (y: number, m1: number, d: number): number =>
	Math.floor(Date.UTC(y, m1 - 1, d) / DAY_MS);
/** Last day of the current BKK month (production default for forecastEnd) */
export function endOfCurrentMonthBkk(nowMs: number): number {
	const dt = new Date(nowMs + BKK_MS);
	return Math.floor(Date.UTC(dt.getUTCFullYear(), dt.getUTCMonth() + 1, 0) / DAY_MS);
}

// ---------------- types ----------------

export type Point = readonly [eventTimeMs: number, rawValue: number];

export interface Analysis {
	night: number;
	daytime: number;
	evening: number;
	day0816: number;
	on: number;
	off: number;
	total: number;
	skipped: number;
	spanDays: number;
	kwhDay: number;
	lastMeter: number;
	t0: number;
	t1: number;
	n: number;
	/** kWh per BKK day (insertion order = chronological first-seen) */
	daily: Map<number, number>;
	/** distinct hours with data per day */
	dayHours: Map<number, Set<number>>;
	dailyOn: Map<number, number>;
	dailyOff: Map<number, number>;
	/** kWh per (day, hour); key = day * 24 + hour */
	dh: Map<number, number>;
	/** average kWh per hour-of-day (sum ÷ days seen) */
	prof: number[];
	/** weekday-only profile, falls back to prof when no weekday samples */
	wdProf: number[];
	daytimeKwhD: number;
	baseloadKw: number;
	eveningKwhD: number;
}

export interface Finance {
	onPct: number;
	offPct: number;
	nightPct: number;
	daytimePct: number;
	eveningPct: number;
	day0816Pct: number;
	measuredMo: number;
	monthlyKwh: number;
	onKwh: number;
	offKwh: number;
	cost1: number;
	cost2: number;
	cost3: number;
	scaleUp: number;
	daytimeLoadD: number;
	usableD: number;
	offsetOn: number;
	offsetOff: number;
	remOn: number;
	remOff: number;
	saveTou: number;
	saveSolar: number;
	beMonths: number;
	tipKwhD: number;
	viable: boolean;
}

export type DayKind = "actual" | "partial" | "today" | "fc";

export interface ForecastDay {
	day: number; // dayNum
	kwh: number;
	kind: DayKind;
	weekend: boolean;
	on: number;
	off: number;
}

export interface Forecast {
	days: ForecastDay[];
	wdAvg: number;
	weAvg: number;
	totalKwh: number;
	futureKwh: number;
	meterEnd: number;
	touCost: number;
	flatCost: number;
	nDays: number;
	forecastEnd: number;
}

export interface SavingsPoint {
	day: number;
	cum: number;
	kind: DayKind;
}

export interface Savings {
	series: SavingsPoint[];
	cumEnd: number;
	avgD: number;
	pct: number;
	/** dayNum of projected break-even, null if no savings */
	beDay: number | null;
	scaleUp: number;
}

// ---------------- 1) load + profile ----------------

/** Python `sorted(set((int(t), float(v)) ...))`: dedupe exact pairs, sort by time then value */
export function toPoints(raw: Iterable<readonly [number | string, number | string]>): Point[] {
	const seen = new Set<string>();
	const pts: [number, number][] = [];
	for (const [t, v] of raw) {
		if (t == null || v == null) continue;
		const tn = Math.trunc(Number(t));
		const vn = Number(v);
		if (!Number.isFinite(tn) || !Number.isFinite(vn)) continue;
		const key = `${tn}|${vn}`;
		if (seen.has(key)) continue;
		seen.add(key);
		pts.push([tn, vn]);
	}
	pts.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
	return pts;
}

export function analyze(pts: Point[]): Analysis {
	let night = 0;
	let daytime = 0;
	let evening = 0;
	let day0816 = 0;
	let on = 0;
	let off = 0;
	let total = 0;
	let skipped = 0;
	const hourly = new Array<number>(24).fill(0);
	const hourSeen: Set<number>[] = Array.from({ length: 24 }, () => new Set());
	const wdHourly = new Array<number>(24).fill(0);
	const wdHourSeen: Set<number>[] = Array.from({ length: 24 }, () => new Set());
	const daily = new Map<number, number>();
	const dayHours = new Map<number, Set<number>>();
	const dailyOn = new Map<number, number>();
	const dailyOff = new Map<number, number>();
	const dh = new Map<number, number>();

	for (let i = 1; i < pts.length; i++) {
		const d = (pts[i][1] - pts[i - 1][1]) * C.SCALE;
		if (d <= 0) continue; // meter reset / no usage
		if (pts[i][0] - pts[i - 1][0] > C.MAX_GAP_MS) {
			skipped += d; // energy real but unattributable to hours
			continue;
		}
		const ms = pts[i][0];
		const h = hourOf(ms);
		const day = dayNum(ms);
		const wd = weekdayOf(day);
		total += d;
		hourly[h] += d;
		hourSeen[h].add(day);
		daily.set(day, (daily.get(day) ?? 0) + d);
		let hrs = dayHours.get(day);
		if (!hrs) {
			hrs = new Set();
			dayHours.set(day, hrs);
		}
		hrs.add(h);
		const dhKey = day * 24 + h;
		dh.set(dhKey, (dh.get(dhKey) ?? 0) + d);
		if (wd < 5) {
			wdHourly[h] += d;
			wdHourSeen[h].add(day);
		}
		if (h >= 9 && h < 17) daytime += d;
		else if (h >= 17 && h < 22) evening += d;
		else night += d;
		if (h >= 8 && h < 16) day0816 += d;
		if (isOnPeakHour(wd, h)) {
			on += d;
			dailyOn.set(day, (dailyOn.get(day) ?? 0) + d);
		} else {
			off += d;
			dailyOff.set(day, (dailyOff.get(day) ?? 0) + d);
		}
	}

	const t0 = pts[0][0];
	const t1 = pts[pts.length - 1][0];
	const spanDays = (t1 - t0) / DAY_MS;
	const prof = hourly.map((sum, h) => (hourSeen[h].size ? sum / hourSeen[h].size : 0));
	const wdProf = wdHourly.map((sum, h) => (wdHourSeen[h].size ? sum / wdHourSeen[h].size : prof[h]));
	let daytimeKwhD = 0;
	for (let h = 9; h < 17; h++) daytimeKwhD += prof[h];
	// Baseload: per complete day (≥23 distinct hours), min hourly kWh → mean
	const mins: number[] = [];
	for (const [day, hrs] of dayHours) {
		if (hrs.size >= 23) {
			let m = Infinity;
			for (const h of hrs) m = Math.min(m, dh.get(day * 24 + h) ?? Infinity);
			mins.push(m);
		}
	}
	const positiveProf = prof.filter((v) => v > 0);
	const baseloadKw = mins.length
		? mins.reduce((s, v) => s + v, 0) / mins.length
		: positiveProf.length
			? Math.min(...positiveProf)
			: 0;
	let eveningKwhD = 0;
	for (let h = 17; h < 22; h++) eveningKwhD += prof[h];

	return {
		night,
		daytime,
		evening,
		day0816,
		on,
		off,
		total,
		skipped,
		spanDays,
		kwhDay: ((pts[pts.length - 1][1] - pts[0][1]) * C.SCALE) / spanDays,
		lastMeter: pts[pts.length - 1][1] * C.SCALE,
		t0,
		t1,
		n: pts.length,
		daily,
		dayHours,
		dailyOn,
		dailyOff,
		dh,
		prof,
		wdProf,
		daytimeKwhD,
		baseloadKw,
		eveningKwhD,
	};
}

// ---------------- 2) financial engine ----------------

export function finance(a: Analysis, useMeaBaseline: boolean = C.USE_MEA_BASELINE): Finance {
	const pct = (v: number) => (a.total ? v / a.total : 0);
	const onPct = pct(a.on);
	const offPct = pct(a.off);
	const measuredMo = a.kwhDay * 30;
	const monthlyKwh = useMeaBaseline ? C.MEA_MONTHLY_KWH : measuredMo;
	const m = monthlyKwh;
	const onKwh = m * onPct;
	const offKwh = m * offPct;
	const cost1 = flatEnergyBaht(m) + C.FLAT_FIXED;
	const cost2 = onKwh * C.TOU_ON + offKwh * C.TOU_OFF + C.TOU_FIXED;
	const scaleUp = measuredMo ? m / measuredMo : 1.0;
	const daytimeLoadD = a.daytimeKwhD * scaleUp;
	const usableD = Math.min(C.SOLAR_KWH_D, daytimeLoadD);
	const offsetOn = Math.min(usableD * C.WEEKDAYS_MO, onKwh);
	const offsetOff = Math.min(usableD * C.WEEKENDS_MO, offKwh);
	const remOn = onKwh - offsetOn;
	const remOff = offKwh - offsetOff;
	const cost3 = remOn * C.TOU_ON + remOff * C.TOU_OFF + C.TOU_FIXED + C.BLUERING;
	const saveTou = cost1 - cost2;
	const saveSolar = cost2 - cost3;
	return {
		onPct,
		offPct,
		nightPct: pct(a.night),
		daytimePct: pct(a.daytime),
		eveningPct: pct(a.evening),
		day0816Pct: pct(a.day0816),
		measuredMo,
		monthlyKwh,
		onKwh,
		offKwh,
		cost1,
		cost2,
		cost3,
		scaleUp,
		daytimeLoadD,
		usableD,
		offsetOn,
		offsetOff,
		remOn,
		remOff,
		saveTou,
		saveSolar,
		beMonths: saveTou > 0 ? C.METER_COST / saveTou : Infinity,
		tipKwhD: C.BLUERING / (C.WEEKDAYS_MO * C.TOU_ON + C.WEEKENDS_MO * C.TOU_OFF),
		viable: cost3 <= cost2,
	};
}

// ---------------- 3) forecast ----------------

export function forecast(a: Analysis, forecastEnd: number): Forecast {
	const complete = new Map<number, number>();
	for (const [day, v] of a.daily) {
		if ((a.dayHours.get(day)?.size ?? 0) >= 23) complete.set(day, v);
	}
	const wdDays: number[] = [];
	const weDays: number[] = [];
	for (const [day, v] of complete) {
		if (weekdayOf(day) < 5) wdDays.push(v);
		else weDays.push(v);
	}
	const wdAvg = wdDays.length ? wdDays.reduce((s, v) => s + v, 0) / wdDays.length : a.kwhDay;
	const weAvg = weDays.length ? weDays.reduce((s, v) => s + v, 0) / weDays.length : wdAvg;
	let wdOn = 0;
	for (let h = 9; h < 22; h++) wdOn += a.wdProf[h];

	const today = dayNum(a.t1);
	const lastHour = hourOf(a.t1);
	const days: ForecastDay[] = [];
	let totalFc = 0;
	let costFc = 0;
	let d = Math.min(...a.daily.keys());
	while (d <= forecastEnd) {
		const wd = weekdayOf(d);
		let kwh: number;
		let kind: DayKind;
		let on: number;
		let off: number;
		if (d < today) {
			kwh = a.daily.get(d) ?? 0;
			kind = (a.dayHours.get(d)?.size ?? 0) < 23 ? "partial" : "actual";
			on = a.dailyOn.get(d) ?? 0;
			off = a.dailyOff.get(d) ?? 0;
		} else if (d === today) {
			// today: actual so far + remaining hours from the profile
			const profile = wd < 5 ? a.wdProf : a.prof;
			let rest = 0;
			for (let h = lastHour + 1; h < 24; h++) rest += profile[h];
			kwh = (a.daily.get(d) ?? 0) + rest;
			kind = "today";
			let onRest = 0;
			if (wd < 5) {
				for (let h = Math.max(lastHour + 1, 9); h < 22; h++) onRest += a.wdProf[h];
			}
			on = (a.dailyOn.get(d) ?? 0) + onRest;
			off = kwh - on;
			totalFc += rest;
		} else {
			kwh = wd < 5 ? wdAvg : weAvg;
			kind = "fc";
			on = wd < 5 ? wdOn : 0;
			on = Math.min(on, kwh);
			off = kwh - on;
			totalFc += kwh;
		}
		costFc += on * C.TOU_ON + off * C.TOU_OFF;
		days.push({ day: d, kwh, kind, weekend: wd >= 5, on, off });
		d += 1;
	}
	const nDays = days.length;
	const totalKwh = days.reduce((s, x) => s + x.kwh, 0);
	// ladder position from the period's month-equivalent volume; service prorated like the TOU side
	const monthEqKwh = nDays > 0 ? (totalKwh * 30) / nDays : 0;
	return {
		days,
		wdAvg,
		weAvg,
		totalKwh,
		futureKwh: totalFc,
		meterEnd: a.lastMeter + totalFc,
		touCost: costFc + C.TOU_FIXED * (nDays / 30),
		flatCost: totalKwh * flatAvgRate(monthEqKwh) + C.FLAT_FIXED * (nDays / 30),
		nDays,
		forecastEnd,
	};
}

// ---------------- 3b) cumulative savings vs meter cost ----------------

export function savingsTrack(f: Finance, fc: Forecast): Savings {
	const scaleUp = f.measuredMo ? f.monthlyKwh / f.measuredMo : 1.0;
	// average tiered rate at the whole-house monthly volume — summing a month of
	// days reproduces the real tiered bill. Service charges (38.22+VAT) are
	// identical on both tariffs, so they cancel and don't appear here.
	const flatRateM = flatAvgRate(f.monthlyKwh);
	let cum = 0;
	const series: SavingsPoint[] = [];
	for (const x of fc.days) {
		const flatD = x.kwh * flatRateM;
		const touEnergyD = x.on * C.TOU_ON + x.off * C.TOU_OFF;
		const saveD = Math.max((flatD - touEnergyD) * scaleUp, 0);
		cum += saveD;
		series.push({ day: x.day, cum, kind: x.kind });
	}
	const avgD = series.length ? cum / series.length : 0;
	const daysToBe = avgD > 0 ? C.METER_COST / avgD : Infinity;
	// Python: date + timedelta(days=float) uses only whole days (truncation)
	const beDay = avgD > 0 ? series[0].day + Math.floor(daysToBe) : null;
	return {
		series,
		cumEnd: cum,
		avgD,
		pct: Math.min((cum / C.METER_COST) * 100, 100),
		beDay,
		scaleUp,
	};
}

// ---------------- 3c) hourly solar production curve ----------------

export function solarCurve(): number[] {
	const shape: number[] = [];
	for (let h = 0; h < 24; h++) {
		const c = h + 0.5;
		shape.push(c >= 6.5 && c <= 17.5 ? Math.max(Math.sin((Math.PI * (c - 6.5)) / 11.0), 0) : 0);
	}
	const s = shape.reduce((a, b) => a + b, 0);
	return shape.map((x) => (x / s) * C.SOLAR_KWH_D);
}

// ---------------- wrapper ----------------

export interface CalcResult {
	a: Analysis;
	f: Finance;
	fc: Forecast;
	sv: Savings;
	sol: number[];
}

/** Returns null when there isn't enough data to analyze */
export function calcAll(
	raw: Iterable<readonly [number | string, number | string]>,
	opts: { forecastEnd?: number; nowMs?: number; useMeaBaseline?: boolean } = {},
): CalcResult | null {
	const pts = toPoints(raw);
	if (pts.length < 2) return null;
	const a = analyze(pts);
	if (a.daily.size === 0) return null;
	const f = finance(a, opts.useMeaBaseline ?? C.USE_MEA_BASELINE);
	const fc = forecast(a, opts.forecastEnd ?? endOfCurrentMonthBkk(opts.nowMs ?? a.t1));
	const sv = savingsTrack(f, fc);
	return { a, f, fc, sv, sol: solarCurve() };
}

// ---------------- calculation trace (Technical Inspector) ----------------

const tf = (x: number, dp = 2) =>
	x.toLocaleString("en-US", { minimumFractionDigits: dp, maximumFractionDigits: dp });

/** Substituted tier breakdown for a monthly volume, e.g. "150×3.2484 + 250×4.2218 + 700×4.4217" */
function tierSubst(kwhMonth: number): string {
	const parts: string[] = [];
	let prev = 0;
	for (const [upto, rate] of FLAT_TIERS) {
		const units = Math.min(kwhMonth, upto) - prev;
		if (units <= 0) break;
		parts.push(`${tf(units, 0)}×${rate}`);
		prev = upto;
	}
	return parts.join(" + ");
}

/** Every headline number as "formula = substituted = result", from the same
 *  objects that render the charts (single source of truth). */
export function traceLines(a: Analysis, f: Finance, fc: Forecast, sv: Savings): string[] {
	return [
		`onPct = on/total = ${tf(a.on)}/${tf(a.total)} = ${(f.onPct * 100).toFixed(1)}%`,
		`offPct = off/total = ${tf(a.off)}/${tf(a.total)} = ${(f.offPct * 100).toFixed(1)}%`,
		`measuredMo = kwhDay×30 = ${tf(a.kwhDay)}×30 = ${tf(f.measuredMo)} kWh`,
		`monthlyKwh = MEA baseline = ${tf(f.monthlyKwh)} kWh`,
		`onKwh = ${tf(f.monthlyKwh)}×${(f.onPct * 100).toFixed(1)}% = ${tf(f.onKwh, 1)} kWh`,
		`offKwh = ${tf(f.monthlyKwh)}×${(f.offPct * 100).toFixed(1)}% = ${tf(f.offKwh, 1)} kWh`,
		`S1 Flat ขั้นบันได = (${tierSubst(f.monthlyKwh)} + ${tf(f.monthlyKwh, 0)}×${C.FT_RATE} Ft)×${C.VAT} VAT + ${C.FLAT_FIXED} = ${tf(f.cost1)} ฿`,
		`flatAvg = ค่าพลังงาน S1 ÷ หน่วย = ${tf(flatAvgRate(f.monthlyKwh), 4)} ฿/kWh (ใช้เกลี่ยรายวันใน savings)`,
		`S2 TOU = ${tf(f.onKwh, 1)}×${C.TOU_ON} + ${tf(f.offKwh, 1)}×${C.TOU_OFF} + ${C.TOU_FIXED} = ${tf(f.onKwh * C.TOU_ON)} + ${tf(f.offKwh * C.TOU_OFF)} + ${tf(C.TOU_FIXED)} = ${tf(f.cost2)} ฿`,
		`scaleUp = monthlyKwh/measuredMo = ${tf(f.monthlyKwh)}/${tf(f.measuredMo)} = ${tf(f.scaleUp)}`,
		`daytimeLoadD = daytimeKwhD×scaleUp = ${tf(a.daytimeKwhD)}×${tf(f.scaleUp)} = ${tf(f.daytimeLoadD)} kWh/วัน`,
		`usable = min(${C.SOLAR_KWH_D}, ${tf(f.daytimeLoadD)}) = ${tf(f.usableD)} kWh/วัน`,
		`offsetOn = min(${tf(f.usableD)}×${C.WEEKDAYS_MO}, ${tf(f.onKwh, 1)}) = ${tf(f.offsetOn, 1)} kWh`,
		`offsetOff = min(${tf(f.usableD)}×${C.WEEKENDS_MO}, ${tf(f.offKwh, 1)}) = ${tf(f.offsetOff, 1)} kWh`,
		`S3 = ${tf(f.remOn, 1)}×${C.TOU_ON} + ${tf(f.remOff, 1)}×${C.TOU_OFF} + ${C.TOU_FIXED} + ${C.BLUERING} = ${tf(f.cost3)} ฿`,
		`saveTou = S1−S2 = ${tf(f.cost1)} − ${tf(f.cost2)} = ${tf(f.saveTou)} ฿/เดือน`,
		`saveSolar = S2−S3 = ${tf(f.cost2)} − ${tf(f.cost3)} = ${tf(f.saveSolar)} ฿/เดือน`,
		`tipping = ${C.BLUERING}/(${C.WEEKDAYS_MO}×${C.TOU_ON} + ${C.WEEKENDS_MO}×${C.TOU_OFF}) = ${tf(f.tipKwhD)} kWh/วัน`,
		`breakEven = ${tf(C.METER_COST)}/${tf(f.saveTou)} = ${Number.isFinite(f.beMonths) ? tf(f.beMonths) : "∞"} เดือน`,
		`forecast wdAvg = ${tf(fc.wdAvg)} kWh/วัน · weAvg = ${tf(fc.weAvg)} kWh/วัน`,
		`savings avg = cum/days = ${tf(sv.cumEnd)}/${sv.series.length} = ${tf(sv.avgD)} ฿/วัน (scaleUp ×${tf(sv.scaleUp)})`,
	];
}
